Feat: add network restore self healing
canonical/mongodb-operator pull request #103
Opened 2022-10-05 10:27 UTC by MiaAltieri

### For the Reader
This is the first PR in a series of PRs, next PRs will cover Integration tests + update in README

### Problem

When the network fails on a unit and comes back up as a different IP this address is not in the cluster and thus `mongod` will not consider it a replica.

### Solution

1. First change the start of `mongod` from `--bind_ip <unit address>` to `--bind_ip_all`, this means when a unit comes back up we do not need to reconfigure and restart the `mongod` service with a new IP address
2. Allow the leader to reconfigure the replica set in `update_status` event handler. In the case that a non-leader looses connection the leader unit will receive a `relation changed event` and update the replica set as necessary. But if the leader is the one that receives a network cut it will need to check for this change in `update_status` when it comes back up

### Release notes:
1. Updated to use `--bind_ip_all`
2. Updated `update_status` to do any reconfigure
3. `update_status` now outputs more verbose status messges.

### Testing

1. Unit tests here check the status message of the unit, this is typically considered poor practice in unit tests. However I have the opinion that status messages should be checked in the case of testing the update status hook

2022-10-05 13:57 UTC, marceloneppel approved these changes
It looks amazing, especially the new statuses.

2022-10-05 20:25 UTC, marcoppenheimer requested changes

2022-10-05 20:25 UTC, marcoppenheimer commented on src/charm.py
> +                self.unit.status = BlockedStatus(replica_status)
Agree with Marcelo, great statuses.

Could these be abstracted somewhere outside `charm.py`?
Purely a suggestion:

`src/utils.py` (or lib equivalent)
```python
def build_unit_status(replset_status, unit: Unit) -> StatusBase:
    if MongodbOperatorCharm._unit_ip(unit) not in replset_status:  # assuming _unit_ip is a static method
        return WaitingStatus("Member being added..")

    if replica_status == "PRIMARY":
        status = ActiveStatus("Replica set primary")
    elif replica_status == "SECONDARY":
        status = ActiveStatus("Replica set secondary")
    elif replica_status in ["STARTUP", "STARTUP2", "ROLLBACK", "RECOVERING"]:
        status = WaitingStatus("Member is syncing..")
    elif replica_status == "REMOVED":
        status = WaitingStatus("Member is removing..")
    else:
        status = BlockedStatus(replica_status)

    return status
```

and then in `src/charm.py`:

```python
self.unit.status = utils.build_unit_status(replset_status=mongo.get_replset_status(), unit=self.unit)
```

2022-10-05 20:25 UTC, marcoppenheimer commented on src/charm.py
> +                self.unit.status = BlockedStatus(replica_status)
Changes 0 logic, it's probably an aesthetic thing, but imo it's helpful having self-contained things like this that aren't strictly about workload management separated, would help when onboarding people to what the charm actually does. And gives you a separate place to extend it, without worrying about messing with the functionality of `update_status()`

2022-10-05 20:25 UTC, marcoppenheimer commented on src/charm.py
> +            logger.debug("only the leader can perform reconfigurations to the replica set.")
Do you want to `return` here if non-leader?
I didn't see `self.update_app_relation_data()` check for leader, could have missed it.

2022-10-06 08:25 UTC, MiaAltieri commented on tests/unit/test_charm.py
> +        self.harness.charm.app_peer_data["db_initialised"] = "True"
Yeah I am fairly certain you need to, I was getting weird errors until I did this :)

2022-10-06 08:35 UTC, MiaAltieri commented on src/charm.py
> +                self.unit.status = BlockedStatus(replica_status)
definitely!! great suggestion!

2022-10-06 10:30 UTC, marcoppenheimer approved these changes

2022-10-06 10:43 UTC, merged