Added documentation landing page
canonical/mongodb-operator pull request #143
Opened 2022-12-13 16:00 UTC by MiaAltieri

Created documentation landing page based around Kubeflow Landing Page

2022-12-13 16:32 UTC, deusebio approved these changes
All good!

2022-12-14 08:42 UTC, delgod requested changes

2022-12-14 08:42 UTC, delgod commented on documentation/documentation_landing.md
> +The Charmed MongoDB Operator delivers automated operations management from day 0 to day 2 on the [MongoDB Community Edition](https://github.com/mongodb/mongo) document database. It is an open source,
I don't think our operator is cloud-native or juju is cloud-native.
```suggestion
The Charmed MongoDB Operator delivers automated operations management from day 0 to day 2 on the [MongoDB Community Edition](https://github.com/mongodb/mongo) document database. It is an open source, end-to-end, production-ready data platform on top of juju.
```

2022-12-15 08:27 UTC, deusebio approved these changes
Looks good, just a couple of suggestion

2022-12-15 09:29 UTC, delgod approved these changes

2022-12-15 10:26 UTC, MiaAltieri commented on documentation/documentation_landing.md
> +| 1 | reference-coming-soon | [Reference -- Coming Soon]() |
We could put I believe these links have to be links to discourse posts?

2022-12-15 14:23 UTC, deusebio commented on documentation/documentation_landing.md
> +| 1 | reference-coming-soon | [Reference -- Coming Soon]() |
If this is not possible, we can of course skip this

2022-12-15 15:16 UTC, merged