change admin user to be named operator
canonical/mongodb-operator pull request #147
Opened 2023-01-10 16:33 UTC by MiaAltieri

2023-01-11 23:03 UTC, WRFitch approved these changes

2023-01-12 09:24 UTC, MiaAltieri commented on lib/charms/tls_certificates_interface/v1/tls_certificates.py
>  from charms.tls_certificates_interface.v1.tls_certificates import (
yes!

2023-01-12 10:51 UTC, delgod requested changes

2023-01-12 10:51 UTC, delgod commented on actions.yaml
> +        Possible values - operator, pbmuser.
lets rename the user to `backup`
```suggestion
        Possible values - operator, backup.
```

2023-01-12 10:51 UTC, delgod commented on lib/charms/mongodb/v0/mongodb.py
> +CHARM_USERS = ["operator", "pbm"]
lets rename the user to `backup`
```suggestion
CHARM_USERS = ["operator", "backup"]
```

2023-01-12 12:04 UTC, delgod approved these changes

2023-01-12 12:04 UTC, delgod commented on actions.yaml
> +        Possible values - operator, pbmuser.
```suggestion
        Possible values - operator, backup.
```

2023-01-12 12:16 UTC, merged