Backup int tests
canonical/mongodb-operator pull request #155
Opened 2023-02-03 16:08 UTC by MiaAltieri

This PR:
1. adds integration tests
2. resolves flakey `pbm` behaviour 
3. adds `endpoint` option for pbm and adds a temporary (not perfect fix) for handling the default endpoint

Integration tests added are:
1. Charmed MongoDB goes into blocked state when given incorrect configurations
4. Charmed MongoDB can create and list backups
5. Stress test: Create a backup, while backing up change configs + bucket and create a new backup. Verify new backups were made 

After analysing the failures in `pbm` to `resync` [(bug here)](https://jira.percona.com/browse/PBM-1038) - the handling of resync needed to be changed from resyncing twice to only resyncing when the `pbm` agent is ready

Please ignore all files under `tests/integration/backups/s3-intergrator`

2023-02-03 18:42 UTC, MiaAltieri commented on tests/integration/backup_tests/test_backups.py
> +
Please wait for relation here to prevent flakey tests

2023-02-08 14:35 UTC, delgod requested changes

2023-02-09 08:22 UTC, MiaAltieri commented on tests/integration/backup_tests/helpers.py
> +    list_result = list_result.split("\n")
Yes, we have begun the conversation. For now I would like to move this [objective to the next cycle](https://warthogs.atlassian.net/browse/DPE-1248) so it doesn't block this PR

2023-02-09 09:19 UTC, MiaAltieri commented on tests/integration/backup_tests/helpers.py
> +        backups += 1 if "logical" in res else 0
True, but we only want to count logical restores since that is the type of restore we are making in this test. I'll rename this function accordingly

2023-02-09 09:20 UTC, MiaAltieri commented on tests/integration/backup_tests/test_backups.py
> +        await ops_test.model.deploy(db_charm, num_units=1)
Thanks for the heads up, I will update this when we get to restores, thank you Mykola 🙏

2023-02-09 17:16 UTC, marceloneppel approved these changes
LGTM! Amazing work, Mia!

2023-02-09 20:13 UTC, delgod approved these changes

2023-02-10 09:36 UTC, merged