Add metrics endpoint
canonical/mongodb-operator pull request #192
Opened 2023-03-22 08:38 UTC by MiaAltieri

### Problem

We need to expose metric endpoint for COS

### Solution

- Provide the relation
- add necessary libs
- use node exporter and mongodb exporter in the charm

### Testing

Verified the endpoint was up with MongoDB related metrics:
```
juju deploy ./*charm
curl http://<unit-ip>:9216/metrics | grep mongo
curl http://<unit-ip>:9100/metrics 
```

### Future PRs

Future PRs will include unit + int tests

### Files to Ignore
`lib/charms/observability_libs/v0/juju_topology.py`
`lib/charms/prometheus_k8s/v0/prometheus_scrape.py`
`src/grafana_dashboards/MongoDB_Cluster_Summary.json`
`src/grafana_dashboards/node-exporter-mongodb.json`

2023-03-22 09:58 UTC, MiaAltieri commented
Closing until next course of action is decided. This is regarding the fact that cos has now changed to the sidecar pattern

2023-03-22 15:14 UTC, zmraul requested changes
This has the dashboards, but is missing the Grafana integration no?
Needs `charmcraft fetch-lib charms.grafana_k8s.v0.grafana_dashboard` and on `charm.py`:
```python
. . .
self.metrics_endpoints = ....
self.grafana_dashboards = GrafanaDashboardProvider(self)
. . .
```

2023-03-22 15:30 UTC, MiaAltieri commented
@zmraul oops you're right I was too hasty in adding the graphana dashboards - I will remove and save for the graphana metric

2023-03-24 08:36 UTC, delgod approved these changes

2023-03-24 08:59 UTC, merged