Bump PyYaml version from '==6.0.0' to '>6.0.0'
canonical/mongodb-operator pull request #237
Opened 2023-08-18 12:12 UTC by dmitry-ratushnyy

## Issue
PyYaml pinned to version 6.0.0 causes issues with building charm

## Solution
Bump PyYaml version

2023-08-21 07:10 UTC, MiaAltieri commented
I think there might be some issues still with compatibility:
```
The conflict is caused by:
    The user requested pyyaml>6.0
    juju 2.9.38.1 depends on pyyaml<=6.0 and >=5.1.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

2023-08-21 07:10 UTC, MiaAltieri reviewed
The conflict is caused by:
    The user requested pyyaml>6.0
    juju 2.9.38.1 depends on pyyaml<=6.0 and >=5.1.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

2023-09-05 11:34 UTC, delgod commented
should be solved via poetry

2023-09-05 16:47 UTC, MiaAltieri requested changes
I believe we have the juju version hardcoded in [the tests to 2.9.38.1](https://github.com/canonical/mongodb-operator/blob/82d0f37a0f247ddd1272d984e3c5223aa6698972/tox.ini#L103) so I think these changes will introduce conflicts with the version of juju we are testing on, it might be necessary to bump that version

2023-09-06 07:36 UTC, dmitry-ratushnyy commented
Closing this PR in favour of https://github.com/canonical/mongodb-operator/pull/240

2023-09-06 07:36 UTC, closed without merging