[DPE-2731] Secret labels + missing unittests
canonical/mongodb-operator pull request #268
Opened 2023-10-12 19:42 UTC by juditnovak

## Issue

Secrets not using labels (and have prototype code)

Furthemore: 200 lines of unittests were missing!!!!!!!!!!!!!!!!!!!!!!!!

## Solution

Adding the same refactor + Secret Labels usage as in the equal [MongoDB K8s PR](https://github.com/canonical/mongodb-k8s-operator/pull/200)

Adding the missing unittests from MongoDB K8s charm

2023-10-13 07:20 UTC, delgod approved these changes

2023-10-13 07:55 UTC, MiaAltieri commented
I thought we decommission `main` - can you make this PR for both `6/edge` and `5/edge`

2023-10-13 07:56 UTC, MiaAltieri requested changes
update target branch

2023-10-13 11:04 UTC, dmitry-ratushnyy approved these changes

2023-10-19 15:03 UTC, juditnovak commented
The contents of this PR were already added in the two PRs referenced above. Closing

2023-10-19 15:03 UTC, closed without merging