Error Checking Service File Reload
canonical/mongodb-operator pull request #40
Opened 2022-06-13 14:35 UTC by MiaAltieri

### Prelude 
Quick Tiny PR for a point @delgod made on a [previous PR](https://github.com/canonical/mongodb-operator/pull/36#discussion_r873593533). 

_Note_ after discussion with @delgod and @WRFitch we decided it best to error check for systemd, but allow permissions to raise exceptions.

### Problem

Reloading service file didn't have any error checking

### Solution

solution add error checking for reloading systemd 

### Testing

Added a unit test to verify behavior in case of failure.

2022-06-13 14:59 UTC, paulomach approved these changes
LGTM

2022-06-13 15:52 UTC, marcoppenheimer requested changes

2022-06-13 15:52 UTC, marcoppenheimer commented on src/charm.py
> +            return
Yeah I'd `raise` instead of return here, as there's the likelihood is that a user will have to fix it.

2022-06-13 15:54 UTC, MiaAltieri commented on src/charm.py
> +            return
Great point! Let me ask the Charming Newbies channel!

2022-06-13 16:05 UTC, marcoppenheimer commented on src/charm.py
> +            return
I'd suggest the following:

```python
except systemd.SystemdError as e:
    self.unit.status = BlockedStatus("failed to reload mongo daemon") # or equivalent
    raise e
```

Raise will give full information in the debug logs.
Status message gives top-line user information

logger.error is not needed

2022-06-14 11:35 UTC, MiaAltieri commented
Closing this pull request as failures in SystemD indicate a greater issue which is out of scope for what this charm should handle.

Further the suggestion of raised exceptions overwrite set status messages and in the solution:
```
        except systemd.SystemdError as e:
            logger.error("failed to reload /etc/systemd/system/mongod.service file, error: %s", e)
            self.unit.status = BlockedStatus("failed to reload MongoDB service")
            raise
```
 `BlockedStatus` gets overwritten by `raise`, and hence becomes unused. It could be changed it to:
```
        except systemd.SystemdError as e:
            logger.error("failed to reload /etc/systemd/system/mongod.service file, error: %s", e)
            raise
```
but this is excessive logging. It is best to allow `systemd.daemon_reload()` to error out

2022-06-14 11:35 UTC, closed without merging