Add upgrade basics
canonical/mongodb-operator pull request #408
Opened 2024-04-23 09:27 UTC by MiaAltieri

## Issue

## Solution

2024-04-23 09:28 UTC, MiaAltieri commented on actions.yaml
> +
copied from OpenSearch

2024-04-23 09:28 UTC, MiaAltieri commented on src/upgrades/mongodb_upgrade.py
> +class MongoDBUpgrade(Object):
most of this is copied from OpenSearch with some changes for MongoDB

2024-04-25 11:07 UTC, carlcsaposs-canonical requested changes

2024-04-25 11:07 UTC, carlcsaposs-canonical commented on actions.yaml
> +      description: Allow unit to upgrade while another unit is starting or stopping
```suggestion
```
(I think) mongodb doesn't have lock; so not relevant

2024-04-25 11:07 UTC, carlcsaposs-canonical commented on charm_version
> +1
nit: add newline

2024-04-25 11:07 UTC, carlcsaposs-canonical commented on metadata.yaml
>      interface: upgrade
nit: copy comment from router & link to spec
https://github.com/canonical/mysql-router-k8s-operator/blob/d64a0d27ab508595698bcae4e9e60f0edfe4546b/metadata.yaml#L45-L49

2024-04-25 11:07 UTC, carlcsaposs-canonical commented on workload_version
> +6.0.6
nit: add newline

2024-04-25 11:07 UTC, carlcsaposs-canonical commented on src/config.py
> +
```suggestion
```
leftover?

2024-04-25 11:07 UTC, carlcsaposs-canonical commented on src/upgrades/machine_upgrade.py
> +        self._unit_databag["workload_version"] = value
changes requested: this was copied incorrectly from opensearch/router

_unit_workload_version was renamed to _unit_workload_container_version and _unit_workload_version was added

2024-04-25 11:07 UTC, carlcsaposs-canonical commented on src/upgrades/mongodb_upgrade.py
> +UPGRADE_RELATION = "upgrade-version-a"
changes requested: please use `upgrade.PEER_RELATION_ENDPOINT_NAME` instead of duplicating constant

2024-04-25 11:07 UTC, carlcsaposs-canonical commented on src/upgrades/mongodb_upgrade.py
> +        self._upgrade.reconcile_partition(action_event=event)
fyi, missing bug fix (not sure if you plan to add in separate pr)

2024-04-25 11:07 UTC, carlcsaposs-canonical commented on src/upgrades/mongodb_upgrade.py
> +        self._upgrade_opensearch_event.emit(ignore_lock=event.params["ignore-lock"])
opensearch event does not exist

also ignore-lock param should be removed

2024-04-25 11:07 UTC, carlcsaposs-canonical commented on src/upgrades/mongodb_upgrade.py
> +            pass
```suggestion
        except upgrade.PeerRelationNotReady:
            pass
```
nit: please avoid changing API of upgrade.py/machine_upgrade.py (will make it more difficult to switch to shared code in future)

2024-04-25 11:31 UTC, MiaAltieri commented on src/upgrades/mongodb_upgrade.py
> +        self._upgrade.reconcile_partition(action_event=event)
yes separate PR :)

2024-04-25 11:32 UTC, MiaAltieri commented on src/upgrades/mongodb_upgrade.py
> +            pass
@carlcsaposs-canonical This fails my linter (I'm suprised it doesn't fail OpenSearch's or MySQL's, custom exceptions should always end with `Error`)

2024-04-25 11:46 UTC, carlcsaposs-canonical commented on src/upgrades/mongodb_upgrade.py
> +            pass
https://github.com/canonical/mysql-router-k8s-operator/blob/50b19ac9060f66d9447bbc77a10ed8ff41df3c0f/pyproject.toml#L104

imo, exceptions should not always end with `Error` because they're not always errors

2024-04-25 12:15 UTC, MiaAltieri commented on src/upgrades/mongodb_upgrade.py
> +            pass
I can support that line of thinking. Thanks for the suggestion Carl, I will revert this and add that to my pyproject.toml <3

2024-04-25 13:59 UTC, MiaAltieri commented on src/upgrades/machine_upgrade.py
> +        self._unit_databag["workload_version"] = value
sounds good:
> _unit_workload_version was renamed to _unit_workload_container_version and _unit_workload_version was added

doing this required other changes throughout that file and upgdade.py, so I just brought those two files up to date with the ones in Charmed Opensearch

2024-04-25 14:14 UTC, carlcsaposs-canonical approved these changes

2024-04-25 14:14 UTC, carlcsaposs-canonical commented on metadata.yaml
> +  # this name corresponds to the version of the upgrade shared-code we currently support
fyi, it's more about the version of the upgrade protocol, not the shared code

(e.g. you could have an update to the shared code without the protocol changing)

ig it'd probably be the major version of the shared code

2024-04-25 14:23 UTC, MiaAltieri commented on metadata.yaml
> +  # this name corresponds to the version of the upgrade shared-code we currently support
I will remove this, one second

2024-04-25 14:25 UTC, MiaAltieri commented on src/upgrades/machine_upgrade.py
> +from upgrades import upgrade
copied from opensearch

2024-04-25 14:26 UTC, MiaAltieri commented on src/upgrades/upgrade.py
> +import enum
copied from opensearch

2024-04-29 10:57 UTC, Mehdi-Bendriss approved these changes

2024-05-27 09:23 UTC, merged