feat(libs): Resolve library version issues
canonical/mongodb-operator pull request #437
Opened 2024-07-24 07:25 UTC by Gu1nness

## Issue

 * Library `set_status` was never published
 * Library `mongodb_tls` was still on 0.X while 1.0 has been published on charmhub.

## Solution

 * Move `mongodb_tls` to v1.1
 * Reset `set_status` to v0.1 so it's published with the right version.

2024-07-24 09:55 UTC, Gu1nness commented
Missing : update on `charm_internal_version` after other PR's are merged.

2024-07-26 07:27 UTC, MiaAltieri requested changes
Looks great! only one change needed!

2024-07-26 07:27 UTC, MiaAltieri commented on lib/charms/mongodb/v1/mongodb_provider.py
> +from charms.mongodb.v1.mongodb import MongoDBConfiguration, MongoDBConnection
this library will need to be bumped to libpatch 7 in order for your change to be published [it is currently at libpatch 6 on charmhub](https://charmhub.io/mongodb/libraries/mongodb_provider) and your change will probably result in some failing charmlib checks

2024-07-26 10:30 UTC, Mehdi-Bendriss submitted a review, later dismissed

2024-07-26 11:47 UTC, MiaAltieri submitted a review, later dismissed

2024-07-26 11:53 UTC, MiaAltieri approved these changes

2024-07-26 12:16 UTC, Mehdi-Bendriss approved these changes

2024-07-26 13:04 UTC, merged