feat(backup): Go to blocked if invalid integration
canonical/mongodb-operator pull request #508
Opened 2024-10-10 11:58 UTC by Gu1nness

## Issue

If integrating s3-integrator to shard, the shard would end up in error state starting from credentials_changed event.

## Solution

In case of invalid integration, we want to go to Blocked state not try to fail the event.

2024-10-10 14:13 UTC, MiaAltieri requested changes

2024-10-10 14:13 UTC, MiaAltieri commented on lib/charms/mongodb/v1/mongodb_backups.py
> +INVALID_INTEGRATION_STATUS = BlockedStatus(
bump libpatch

2024-10-10 14:14 UTC, Gu1nness commented on lib/charms/mongodb/v1/mongodb_backups.py
> +INVALID_INTEGRATION_STATUS = BlockedStatus(
Done :)

2024-10-10 14:15 UTC, MiaAltieri approved these changes

2024-10-11 08:18 UTC, skourta approved these changes

2024-10-11 10:07 UTC, merged